version: "1"
services:
  - type: web
    name: my-app
    runtime: node 
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
