version: "1"
services:
  - type: web
    name: my-app
    runtime: node 
    buildCommand: "yarn install"
    startCommand: "yarn start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
